package jobs

import (
	"fmt"
	"sync"
	"sync/atomic"
)

// Source struct'ınızın ve maxItemsToFetch sabitinizin bu dosyada veya
// paketin başka bir yerinde tanımlı olduğunu varsayıyorum.
// type Source struct {
// 	Name      string
// 	URL       string
// 	Processor func(string, string) (bool, error)
// }
// const maxItemsToFetch = 100

func Data() {
	// Sadece çalışan ve benzersiz kaynakların listesi
	sources := []Source{
		{"Reddit", fmt.Sprintf("https://www.reddit.com/r/popular.json?limit=%d", maxItemsToFetch), processReddit},
		{"Mastodon", fmt.Sprintf("https://mastodon.social/api/v1/timelines/public?limit=%d", maxItemsToFetch), processMastodon},
		{"Lobsters", "https://lobste.rs/hottest.json", processLobsters},
		{"Slashdot", "https://slashdot.org/slashdot.xml", processSlashdot},
		{"StackExchange", fmt.Sprintf("https://api.stackexchange.com/2.3/questions?order=desc&sort=hot&site=stackoverflow&pagesize=%d&filter=withbody", maxItemsToFetch), processStackExchange},
		{"DevTo", fmt.Sprintf("https://dev.to/api/articles?per_page=%d", maxItemsToFetch), processDevTo},
		{"GitHub Trending", "https://api.github.com/search/repositories?q=created:>2024-01-01&sort=stars&order=desc&per_page=100", processGitHubTrending},
		{"InfoQ", "https://feed.infoq.com/", processRSSFeed},
		{"Smashing Magazine", "https://www.smashingmagazine.com/feed/", processRSSFeed},
		{"CSS Tricks", "https://css-tricks.com/feed/", processRSSFeed},
		{"A List Apart", "https://alistapart.com/main/feed/", processRSSFeed},
		{"SitePoint", "https://www.sitepoint.com/feed/", processRSSFeed},
		{"Tuts+", "https://code.tutsplus.com/posts.atom", processRSSFeed},
		{"Codrops", "https://tympanus.net/codrops/feed/", processRSSFeed},
		{"Go Blog", "https://blog.golang.org/feed.atom", processRSSFeed},
		{"Python Blog", "https://blog.python.org/feeds/posts/default", processRSSFeed},
		{"Rust Blog", "https://blog.rust-lang.org/feed.xml", processRSSFeed},
		{"TechCrunch", "https://techcrunch.com/feed/", processRSSFeed},
		{"VentureBeat", "https://venturebeat.com/feed/", processRSSFeed},
		{"ReadWrite", "https://readwrite.com/feed/", processRSSFeed},
		{"Engadget", "https://www.engadget.com/rss.xml", processRSSFeed},
		{"Gizmodo", "https://gizmodo.com/rss", processRSSFeed},
		{"Ben Thompson", "https://stratechery.com/feed/", processRSSFeed},
		{"MacRumors", "https://www.macrumors.com/feed/", processRSSFeed},
		{"9to5Mac", "https://9to5mac.com/feed/", processRSSFeed},
		{"9to5Google", "https://9to5google.com/feed/", processRSSFeed},
		{"TechRadar", "https://www.techradar.com/rss", processRSSFeed},
		{"CNET", "https://www.cnet.com/rss/all/", processRSSFeed},
		{"ZDNet", "https://www.zdnet.com/news/rss.xml", processRSSFeed},
		{"AnandTech", "https://www.anandtech.com/rss/", processRSSFeed},
		{"High Scalability", "http://feeds.feedburner.com/HighScalability", processRSSFeed},
		{"The New Stack", "https://thenewstack.io/feed/", processRSSFeed},
		{"Container Journal", "https://containerjournal.com/feed/", processRSSFeed},
		{"DevOps.com", "https://devops.com/feed/", processRSSFeed},
		{"The Register", "https://www.theregister.com/feed/", processRSSFeed},
		{"InfoWorld", "https://www.infoworld.com/index.rss", processRSSFeed},
		{"SD Times", "https://sdtimes.com/feed/", processRSSFeed},
		{"C# Blog", "https://devblogs.microsoft.com/dotnet/feed/", processRSSFeed},
		{"PHP Blog", "https://php.net/feed.atom", processRSSFeed},
		{"Ruby Blog", "https://www.ruby-lang.org/en/feeds/news.rss", processRSSFeed},
		{"Swift Blog", "https://swift.org/atom.xml", processRSSFeed},
		{"Kotlin Blog", "https://blog.jetbrains.com/kotlin/feed/", processRSSFeed},
		{"TypeScript Blog", "https://devblogs.microsoft.com/typescript/feed/", processRSSFeed},
		{"Scala Blog", "https://www.scala-lang.org/feed.xml", processRSSFeed},
		{"Clojure Blog", "https://clojure.org/feed.xml", processRSSFeed},
		{"Elixir Blog", "https://elixir-lang.org/blog/feed.xml", processRSSFeed},
		{"Haskell Blog", "https://haskell.org/atom.xml", processRSSFeed},
		{"F# Blog", "https://devblogs.microsoft.com/dotnet/category/fsharp/feed/", processRSSFeed},
		{"Julia Blog", "https://julialang.org/blog/feed.xml", processRSSFeed},
		{"Nim Blog", "https://nim-lang.org/feed.xml", processRSSFeed},
		{"Crystal Blog", "https://crystal-lang.org/feed.xml", processRSSFeed},
		{"Zig Blog", "https://ziglang.org/news/rss.xml", processRSSFeed},
		{"V Blog", "https://vlang.io/feed.xml", processRSSFeed},
		{"Web.dev", "https://web.dev/feed.xml", processRSSFeed},
		{"Web Designer News", "https://www.webdesignernews.com/feed", processRSSFeed},
		{"CSS Weekly", "https://css-weekly.com/feed/", processRSSFeed},
		{"JavaScript Weekly", "https://javascriptweekly.com/rss/", processRSSFeed},
		{"Node Weekly", "https://nodeweekly.com/rss/", processRSSFeed},
		{"React Status", "https://react.statuscode.com/rss/", processRSSFeed},
		{"Vue.js Feed", "https://vuejsfeed.com/rss.xml", processRSSFeed},
		{"Angular Blog", "https://blog.angular.io/feed", processRSSFeed},
		{"Svelte Blog", "https://svelte.dev/blog/rss.xml", processRSSFeed},
		{"Ember.js Blog", "https://blog.emberjs.com/feed.xml", processRSSFeed},
		{"jQuery Blog", "https://blog.jquery.com/feed/", processRSSFeed},
		{"Bootstrap Blog", "https://blog.getbootstrap.com/feed/", processRSSFeed},
		{"Tailwind CSS Blog", "https://tailwindcss.com/blog/rss.xml", processRSSFeed},
		{"Bulma Blog", "https://bulma.io/feed.xml", processRSSFeed},
		{"Android Developers Blog", "https://android-developers.googleblog.com/feeds/posts/default", processRSSFeed},
		{"iOS Dev Weekly", "https://iosdevweekly.com/rss/", processRSSFeed},
		{"React Native Blog", "https://reactnative.dev/blog/feed.xml", processRSSFeed},
		{"Flutter Blog", "https://medium.com/flutter/feed", processRSSFeed},
		{"Xamarin Blog", "https://devblogs.microsoft.com/xamarin/feed/", processRSSFeed},
		{"Ionic Blog", "https://ionicframework.com/blog/feed.xml", processRSSFeed},
		{"Cordova Blog", "https://cordova.apache.org/blog/feed.xml", processRSSFeed},
		{"Unity Blog", "https://blog.unity.com/feed", processRSSFeed},
		{"Unreal Engine Blog", "https://www.unrealengine.com/en-US/feed", processRSSFeed},
		{"Game Developer", "https://www.gamedeveloper.com/rss.xml", processRSSFeed},
		{"Polygon", "https://www.polygon.com/rss/index.xml", processRSSFeed},
		{"Kotaku", "https://kotaku.com/rss", processRSSFeed},
		{"IGN", "https://www.ign.com/feed.xml", processRSSFeed},
		{"Towards Data Science", "https://towardsdatascience.com/feed", processRSSFeed},
		{"KDnuggets", "https://www.kdnuggets.com/feed", processRSSFeed},
		{"Analytics Vidhya", "https://www.analyticsvidhya.com/feed/", processRSSFeed},
		{"R-bloggers", "https://www.r-bloggers.com/feed/", processRSSFeed},
		{"Machine Learning Mastery", "https://machinelearningmastery.com/feed/", processRSSFeed},
		{"Distill", "https://distill.pub/rss.xml", processRSSFeed},
		{"Papers With Code", "https://paperswithcode.com/rss", processRSSFeed},
		{"OpenAI Blog", "https://openai.com/blog/rss.xml", processRSSFeed},
		{"Google AI Blog", "https://ai.googleblog.com/feeds/posts/default", processRSSFeed},
		{"DeepMind Blog", "https://deepmind.com/blog/feed/basic/", processRSSFeed},
		{"Microsoft AI Blog", "https://blogs.microsoft.com/ai/feed/", processRSSFeed},
		{"Facebook AI Blog", "https://ai.facebook.com/blog/rss/", processRSSFeed},
		{"NVIDIA AI Blog", "https://blogs.nvidia.com/feed/", processRSSFeed},
		{"Intel AI Blog", "https://www.intel.com/content/www/us/en/artificial-intelligence/ai-in-production/feed.xml", processRSSFeed},
		{"Ethereum Blog", "https://blog.ethereum.org/feed.xml", processRSSFeed},
		{"Bitcoin Magazine", "https://bitcoinmagazine.com/feed", processRSSFeed},
		{"CoinDesk", "https://www.coindesk.com/feed", processRSSFeed},
		{"Cointelegraph", "https://cointelegraph.com/rss", processRSSFeed},
		{"The Block", "https://www.theblock.co/rss.xml", processRSSFeed},
		{"Decrypt", "https://decrypt.co/feed", processRSSFeed},
		{"CryptoSlate", "https://cryptoslate.com/feed/", processRSSFeed},
		{"Bitcoin.com", "https://news.bitcoin.com/feed/", processRSSFeed},
		{"Arduino Blog", "https://blog.arduino.cc/feed/", processRSSFeed},
		{"Raspberry Pi Blog", "https://www.raspberrypi.org/blog/feed/", processRSSFeed},
		{"Adafruit Blog", "https://blog.adafruit.com/feed/", processRSSFeed},
		{"SparkFun Blog", "https://www.sparkfun.com/news/feed", processRSSFeed},
		{"Hackster.io", "https://www.hackster.io/feed", processRSSFeed},
		{"Instructables", "https://www.instructables.com/feed/", processRSSFeed},
		{"Make Magazine", "https://makezine.com/feed/", processRSSFeed},
		{"Linux Foundation Blog", "https://www.linuxfoundation.org/feed/", processRSSFeed},
		{"Red Hat Blog", "https://www.redhat.com/en/blog/feed", processRSSFeed},
		{"Canonical Blog", "https://ubuntu.com/blog/feed", processRSSFeed},
		{"SUSE Blog", "https://www.suse.com/c/feed/", processRSSFeed},
		{"Fedora Magazine", "https://fedoramagazine.org/feed/", processRSSFeed},
		{"Arch Linux News", "https://archlinux.org/feeds/news.xml", processRSSFeed},
		{"LWN.net", "https://lwn.net/headlines/rss", processRSSFeed},
		{"Phoronix", "https://www.phoronix.com/rss.php", processRSSFeed},
		{"MongoDB Blog", "https://www.mongodb.com/blog/feed", processRSSFeed},
		{"MySQL Blog", "https://mysqlserverteam.com/feed/", processRSSFeed},
		{"Redis Blog", "https://redis.io/feed.xml", processRSSFeed},
		{"Cassandra Blog", "https://cassandra.apache.org/blog/feed.xml", processRSSFeed},
		{"Elastic Blog", "https://www.elastic.co/blog/feed", processRSSFeed},
		{"InfluxData Blog", "https://www.influxdata.com/blog/feed/", processRSSFeed},
		{"TimescaleDB Blog", "https://blog.timescale.com/feed/", processRSSFeed},
		{"CockroachDB Blog", "https://www.cockroachlabs.com/blog/feed/", processRSSFeed},
		{"Neo4j Blog", "https://neo4j.com/blog/feed/", processRSSFeed},
		{"ArangoDB Blog", "https://www.arangodb.com/blog/feed/", processRSSFeed},
		{"CouchDB Blog", "https://blog.couchdb.org/feed/", processRSSFeed},
		{"RethinkDB Blog", "https://rethinkdb.com/blog/feed.xml", processRSSFeed},
		{"Docker Blog", "https://www.docker.com/blog/feed/", processRSSFeed},
		{"Kubernetes Blog", "https://kubernetes.io/feed.xml", processRSSFeed},
		{"HashiCorp Blog", "https://www.hashicorp.com/blog/feed.xml", processRSSFeed},
		{"Ansible Blog", "https://www.ansible.com/blog/feed", processRSSFeed},
		{"Chef Blog", "https://blog.chef.io/feed/", processRSSFeed},
		{"Puppet Blog", "https://puppet.com/blog/feed/", processRSSFeed},
		{"Jenkins Blog", "https://jenkins.io/blog/feed.xml", processRSSFeed},
		{"GitHub Blog", "https://github.blog/feed/", processRSSFeed},
		{"Bitbucket Blog", "https://bitbucket.org/blog/feed", processRSSFeed},
		{"Atlassian Blog", "https://blog.atlassian.com/feed/", processRSSFeed},
		{"CircleCI Blog", "https://circleci.com/blog/feed.xml", processRSSFeed},
		{"AWS News", "https://aws.amazon.com/blogs/aws/feed/", processRSSFeed},
		{"Google Cloud Blog", "https://cloudblog.withgoogle.com/rss/", processRSSFeed},
		{"Microsoft Azure Blog", "https://azure.microsoft.com/en-us/blog/feed/", processRSSFeed},
		{"DigitalOcean Blog", "https://www.digitalocean.com/blog/feed", processRSSFeed},
		{"Heroku Blog", "https://blog.heroku.com/feed", processRSSFeed},
		{"Vercel Blog", "https://vercel.com/blog/feed", processRSSFeed},
		{"Netlify Blog", "https://www.netlify.com/blog/feed/", processRSSFeed},
		{"Cloudflare Blog", "https://blog.cloudflare.com/rss/", processRSSFeed},
		{"Fastly Blog", "https://www.fastly.com/blog/feed", processRSSFeed},
		{"Schneier on Security", "https://www.schneier.com/feed/", processRSSFeed},
		{"Krebs on Security", "https://krebsonsecurity.com/feed/", processRSSFeed},
		{"The Hacker News", "https://feeds.feedburner.com/TheHackersNews", processRSSFeed},
		{"Security Weekly", "https://securityweekly.com/feed/", processRSSFeed},
		{"Dark Reading", "https://www.darkreading.com/rss.xml", processRSSFeed},
		{"SANS Internet Storm Center", "https://isc.sans.edu/rssfeed.xml", processRSSFeed},
		{"Naked Security", "https://nakedsecurity.sophos.com/feed/", processRSSFeed},
		{"Troy Hunt", "https://www.troyhunt.com/rss/", processRSSFeed},
		{"Electronic Frontier Foundation", "https://www.eff.org/rss/updates.xml", processRSSFeed},
		{"Netflix Tech Blog", "https://netflixtechblog.com/feed", processRSSFeed},
		{"Uber Engineering", "https://eng.uber.com/feed/", processRSSFeed},
		{"Airbnb Engineering", "https://medium.com/airbnb-engineering/feed", processRSSFeed},
		{"Spotify Engineering", "https://engineering.atspotify.com/feed/", processRSSFeed},
		{"Dropbox Tech Blog", "https://dropbox.tech/feed", processRSSFeed},
		{"Slack Engineering", "https://slack.engineering/feed/", processRSSFeed},
		{"GitHub Engineering", "https://github.blog/category/engineering/feed/", processRSSFeed},
		{"Shopify Engineering", "https://shopify.engineering/feed", processRSSFeed},
		{"Stripe Blog", "https://stripe.com/blog/feed", processRSSFeed},
		{"Twilio Blog", "https://www.twilio.com/blog/feed", processRSSFeed},
		{"SendGrid Blog", "https://sendgrid.com/blog/feed/", processRSSFeed},
		{"Auth0 Blog", "https://auth0.com/blog/feed/", processRSSFeed},
		{"Okta Developer Blog", "https://developer.okta.com/blog/feed/", processRSSFeed},
		{"Plaid Blog", "https://blog.plaid.com/feed/", processRSSFeed},
		{"Segment Blog", "https://segment.com/blog/feed/", processRSSFeed},
		{"Intercom Blog", "https://www.intercom.com/blog/feed/", processRSSFeed},
		{"Zapier Blog", "https://zapier.com/blog/feed/", processRSSFeed},
		{"Notion Blog", "https://www.notion.so/blog/feed", processRSSFeed},
		{"Figma Blog", "https://www.figma.com/blog/feed/", processRSSFeed},
		{"Webflow Blog", "https://webflow.com/blog/feed", processRSSFeed},
		{"JetBrains Blog", "https://blog.jetbrains.com/feed/", processRSSFeed},
		{"Visual Studio Blog", "https://devblogs.microsoft.com/visualstudio/feed/", processRSSFeed},
		{"VS Code Blog", "https://code.visualstudio.com/feed.xml", processRSSFeed},
		{"IntelliJ IDEA Blog", "https://blog.jetbrains.com/idea/feed/", processRSSFeed},
		{"Selenium Blog", "https://selenium.dev/blog/feed.xml", processRSSFeed},
		{"Jest Blog", "https://jestjs.io/blog/feed.xml", processRSSFeed},
		{"GTmetrix Blog", "https://gtmetrix.com/blog/feed/", processRSSFeed},
		{"Pingdom Blog", "https://www.pingdom.com/blog/feed/", processRSSFeed},
		{"New Relic Blog", "https://blog.newrelic.com/feed/", processRSSFeed},
		{"Datadog Blog", "https://www.datadoghq.com/blog/feed/", processRSSFeed},
		{"Sentry Blog", "https://blog.sentry.io/feed/", processRSSFeed},
		{"LogRocket Blog", "https://blog.logrocket.com/feed/", processRSSFeed},
		{"Bugsnag Blog", "https://blog.bugsnag.com/feed/", processRSSFeed},
		{"Rollbar Blog", "https://rollbar.com/blog/feed/", processRSSFeed},
		{"WebAIM Blog", "https://webaim.org/blog/feed/", processRSSFeed},
		{"A11y Project", "https://www.a11yproject.com/feed/", processRSSFeed},
		{"UX Planet", "https://uxplanet.org/feed", processRSSFeed},
		{"UX Design", "https://uxdesign.cc/feed", processRSSFeed},
		{"Nielsen Norman Group", "https://www.nngroup.com/feed/", processRSSFeed},
		{"UX Booth", "https://www.uxbooth.com/feed/", processRSSFeed},
		{"UX Movement", "https://uxmovement.com/feed/", processRSSFeed},
		{"UX Matters", "https://www.uxmatters.com/rss/", processRSSFeed},
		{"Stack Overflow Blog", "https://stackoverflow.blog/feed/", processRSSFeed},
		{"Dev.to", "https://dev.to/feed", processRSSFeed},
		{"Medium Programming", "https://medium.com/tag/programming/feed", processRSSFeed},
		{"FreeCodeCamp", "https://www.freecodecamp.org/news/feed/", processRSSFeed},
		{"Pluralsight Blog", "https://www.pluralsight.com/blog/feed", processRSSFeed},
		{"Udemy Blog", "https://blog.udemy.com/feed/", processRSSFeed},
		{"Coursera Blog", "https://blog.coursera.org/feed/", processRSSFeed},
		{"edX Blog", "https://blog.edx.org/feed/", processRSSFeed},
		{"The Verge", "https://www.theverge.com/rss/index.xml", processRSSFeed},
		{"Wired", "https://www.wired.com/feed/rss", processRSSFeed},
		{"MIT Technology Review", "https://www.technologyreview.com/feed/", processRSSFeed},
		{"Recode", "https://www.vox.com/rss/recode/index.xml", processRSSFeed},
		{"Daring Fireball", "https://daringfireball.net/feeds/main", processRSSFeed},
		{"Six Colors", "https://sixcolors.com/feed/", processRSSFeed},
		{"Android Police", "https://www.androidpolice.com/feed/", processRSSFeed},
		{"The Next Web", "https://thenextweb.com/feed/", processRSSFeed},
		{"Digital Trends", "https://www.digitaltrends.com/feed/", processRSSFeed},
		{"Tom's Hardware", "https://www.tomshardware.com/feeds/all", processRSSFeed},
		{"Ars Technica", "https://feeds.arstechnica.com/arstechnica/index", processRSSFeed},
		{"Daily Telegraph (AU)", "https://www.dailytelegraph.com.au/news/breaking-news/rss", processRSSFeed},
		{"Sydney Morning Herald", "https://www.smh.com.au/rss/feed.xml", processRSSFeed},
		{"Herald Sun", "https://www.heraldsun.com.au/news/breaking-news/rss", processRSSFeed},
		{"ABC News (AU)", "https://www.abc.net.au/news/feed/1948/rss.xml", processRSSFeed},
		{"The Age", "https://www.theage.com.au/rss/feed.xml", processRSSFeed},
		{"The Courier Mail", "https://www.couriermail.com.au/rss", processRSSFeed},
		{"The Canberra Times", "https://www.canberratimes.com.au/rss.xml", processRSSFeed},
		{"Brisbane Times", "https://www.brisbanetimes.com.au/rss/feed.xml", processRSSFeed},
		{"InDaily", "https://indaily.com.au/feed/", processRSSFeed},
		{"The Mercury", "https://www.themercury.com.au/rss", processRSSFeed},
		{"bdnews24.com", "https://bdnews24.com/?widgetName=rssfeed&widgetId=1150&getXmlFeed=true", processRSSFeed},
		{"Folha de S.Paulo", "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml", processRSSFeed},
		{"CBC Top Stories", "https://www.cbc.ca/cmlink/rss-topstories", processRSSFeed},
		{"CTVNews.ca Top Stories", "https://www.ctvnews.ca/rss/ctvnews-ca-top-stories-public-rss-1.822009", processRSSFeed},
		{"Global News Canada", "https://globalnews.ca/feed/", processRSSFeed},
		{"Financial Post", "https://business.financialpost.com/feed/", processRSSFeed},
		{"National Post", "https://nationalpost.com/feed/", processRSSFeed},
		{"ZEIT ONLINE", "http://newsfeed.zeit.de/index", processRSSFeed},
		{"FOCUS Online", "https://rss.focus.de/fol/XML/rss_folnews.xml", processRSSFeed},
		{"FAZ.NET", "https://www.faz.net/rss/aktuell/", processRSSFeed},
		{"tagesschau.de", "http://www.tagesschau.de/xml/rss2", processRSSFeed},
		{"Deutsche Welle", "https://rss.dw.com/rdf/rss-en-all", processRSSFeed},
		{"france24.com", "https://www.france24.com/en/rss", processRSSFeed},
		{"Le Monde.fr", "https://www.lemonde.fr/rss/une.xml", processRSSFeed},
		{"L'Obs", "https://www.nouvelobs.com/a-la-une/rss.xml", processRSSFeed},
		{"Le Huffington Post (FR)", "https://www.huffingtonpost.fr/feeds/index.xml", processRSSFeed},
		{"BBC News Home", "http://feeds.bbci.co.uk/news/rss.xml", processRSSFeed},
		{"The Guardian World", "https://www.theguardian.com/world/rss", processRSSFeed},
		{"The Independent UK", "http://www.independent.co.uk/news/uk/rss", processRSSFeed},
		{"BBC News - India", "http://feeds.bbci.co.uk/news/world/asia/india/rss.xml", processRSSFeed},
		{"The Guardian - India", "https://www.theguardian.com/world/india/rss", processRSSFeed},
		{"Times of India", "https://timesofindia.indiatimes.com/rssfeedstopstories.cms", processRSSFeed},
		{"The Hindu", "https://www.thehindu.com/feeder/default.rss", processRSSFeed},
		{"NDTV News", "https://feeds.feedburner.com/ndtvnews-top-stories", processRSSFeed},
		{"India Today", "https://www.indiatoday.in/rss/home", processRSSFeed},
		{"The Indian Express", "http://indianexpress.com/print/front-page/feed/", processRSSFeed},
		{"Firstpost India", "https://www.firstpost.com/rss/india.xml", processRSSFeed},
		{"Business Standard India", "https://www.business-standard.com/rss/home_page_top_stories.rss", processRSSFeed},
		{"The Financial Express India", "https://www.financialexpress.com/feed/", processRSSFeed},
		{"Business Line", "https://www.thehindubusinessline.com/feeder/default.rss", processRSSFeed},
		{"HuffPost World News", "https://www.huffpost.com/section/world-news/feed", processRSSFeed},
		{"NYT Top Stories", "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", processRSSFeed},
		{"FOX News", "http://feeds.foxnews.com/foxnews/latest", processRSSFeed},
		{"Washington Post World", "http://feeds.washingtonpost.com/rss/world", processRSSFeed},
		{"WSJ World News", "https://feeds.a.dj.com/rss/RSSWorldNews.xml", processRSSFeed},
		{"LA Times World & Nation", "https://www.latimes.com/world-nation/rss2.0.xml", processRSSFeed},
		{"CNN International", "http://rss.cnn.com/rss/edition.rss", processRSSFeed},
		{"Yahoo News", "https://news.yahoo.com/rss/mostviewed", processRSSFeed},
		{"CNBC Top News", "https://www.cnbc.com/id/100003114/device/rss/rss.html", processRSSFeed},
		{"Politico Playbook", "https://rss.politico.com/playbook.xml", processRSSFeed},
		{"All About Android (Audio)", "https://feeds.twit.tv/aaa.xml", processRSSFeed},
		{"Android Authority", "https://www.androidauthority.com/feed", processRSSFeed},
		{"Android Community", "https://androidcommunity.com/feed/", processRSSFeed},
		{"AndroidGuys", "https://www.androidguys.com/feed", processRSSFeed},
		{"Droid Life", "https://www.droid-life.com/feed", processRSSFeed},
		{"Android Developers Backstage", "http://feeds.feedburner.com/blogspot/androiddevelopersbackstage", processRSSFeed},
		{"Fragmented Podcast", "https://feeds.simplecast.com/LpAGSLnY", processRSSFeed},
		{"Cult of Mac", "https://www.cultofmac.com/feed", processRSSFeed},
		{"MacStories", "https://www.macstories.net/feed", processRSSFeed},
		{"Macworld", "https://www.macworld.com/index.rss", processRSSFeed},
		{"The Loop", "https://www.loopinsight.com/feed", processRSSFeed},
		{"iMore", "http://feeds.feedburner.com/TheiPhoneBlog", processRSSFeed},
		{"r/iPhone", "https://www.reddit.com/r/iphone/.rss", processRSSFeed},
		{"Swift by Sundell", "https://www.swiftbysundell.com/feed.rss", processRSSFeed},
		{"ArchDaily", "http://feeds.feedburner.com/Archdaily", processRSSFeed},
		{"Dezeen Architecture", "https://www.dezeen.com/architecture/feed/", processRSSFeed},
		{"Architectural Digest", "https://www.architecturaldigest.com/feed/rss", processRSSFeed},
		{"Contemporist", "https://www.contemporist.com/feed/", processRSSFeed},
		{"Design Milk Architecture", "https://design-milk.com/category/architecture/feed/", processRSSFeed},
		{"Book Riot", "https://bookriot.com/feed/", processRSSFeed},
		{"Kirkus Reviews", "https://www.kirkusreviews.com/feeds/rss/", processRSSFeed},
		{"r/books", "https://reddit.com/r/books/.rss", processRSSFeed},
		{"Investing.com News", "https://www.investing.com/rss/news.rss", processRSSFeed},
		{"Seeking Alpha", "https://seekingalpha.com/market_currents.xml", processRSSFeed},
		{"Forbes - Business", "https://www.forbes.com/business/feed/", processRSSFeed},
		{"Fortune", "https://fortune.com/feed", processRSSFeed},
		{"HBR IdeaCast", "http://feeds.harvardbusiness.org/harvardbusiness/ideacast", processRSSFeed},
		{"How I Built This", "https://feeds.npr.org/510313/podcast.xml", processRSSFeed},
		{"Tim Ferriss Blog", "https://tim.blog/feed/", processRSSFeed},
		{"Yahoo Finance", "https://finance.yahoo.com/news/rssindex", processRSSFeed},
		{"Autoblog", "https://www.autoblog.com/rss.xml", processRSSFeed},
		{"Autocar", "https://www.autocar.co.uk/rss", processRSSFeed},
		{"Jalopnik", "https://jalopnik.com/rss", processRSSFeed},
		{"Car and Driver", "https://www.caranddriver.com/rss/all.xml/", processRSSFeed},
		{"r/formula1", "https://www.reddit.com/r/formula1/.rss", processRSSFeed},
		{"101 Cookbooks", "https://www.101cookbooks.com/feed", processRSSFeed},
		{"Food52", "http://feeds.feedburner.com/food52-TheAandMBlog", processRSSFeed},
		{"Serious Eats", "http://feeds.feedburner.com/seriouseats/recipes", processRSSFeed},
		{"Smitten Kitchen", "http://feeds.feedburner.com/smittenkitchen", processRSSFeed},
		{"NYT Food", "https://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml", processRSSFeed},
		{"Eurogamer.net", "https://www.eurogamer.net/?format=rss", processRSSFeed},
		{"Gamasutra", "http://feeds.feedburner.com/GamasutraNews", processRSSFeed},
		{"GameSpot", "https://www.gamespot.com/feeds/mashup/", processRSSFeed},
		{"Rock, Paper, Shotgun", "http://feeds.feedburner.com/RockPaperShotgun", processRSSFeed},
		{"r/gaming", "https://www.reddit.com/r/gaming.rss", processRSSFeed},
		{"Coding Horror", "https://feeds.feedburner.com/codinghorror", processRSSFeed},
		{"Developer Tea", "https://feeds.simplecast.com/dLRotFGk", processRSSFeed},
		{"Martin Fowler", "https://martinfowler.com/feed.atom", processRSSFeed},
		{"HackerNoon", "https://medium.com/feed/hackernoon", processRSSFeed},
		{"r/programming", "https://www.reddit.com/r/programming/.rss", processRSSFeed},
		{"Scientific American", "http://rss.sciam.com/sciam/60secsciencepodcast", processRSSFeed},
		{"BBC News Science", "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml", processRSSFeed},
		{"FlowingData", "https://flowingdata.com/feed", processRSSFeed},
		{"Hidden Brain", "https://feeds.npr.org/510308/podcast.xml", processRSSFeed},
		{"ScienceDaily", "https://www.sciencedaily.com/rss/all.xml", processRSSFeed},
		{"NYT Science", "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml", processRSSFeed},
		{"Nature", "https://www.nature.com/nature.rss", processRSSFeed},
		{"Phys.org", "https://phys.org/rss-feed/", processRSSFeed},
		{"Radiolab", "http://feeds.wnyc.org/radiolab", processRSSFeed},
		{"r/science", "https://reddit.com/r/science/.rss", processRSSFeed},
		{"TED Talks Daily", "https://pa.tedcdn.com/feeds/talks.rss", processRSSFeed},
		{"r/space", "https://www.reddit.com/r/space/.rss?format=xml", processRSSFeed},
		{"NASA Breaking News", "https://www.nasa.gov/rss/dyn/breaking_news.rss", processRSSFeed},
		{"New Scientist - Space", "https://www.newscientist.com/subject/space/feed/", processRSSFeed},
		{"The Guardian - Space", "https://www.theguardian.com/science/space/rss", processRSSFeed},
		{"Space.com", "https://www.space.com/feeds/all", processRSSFeed},
		{"SpaceX YouTube", "https://www.youtube.com/feeds/videos.xml?user=spacexchannel", processRSSFeed},
		{"Designer News", "https://www.designernews.co/?format=rss", processRSSFeed},
		{"Inside Design (Invision)", "https://www.invisionapp.com/inside-design/feed", processRSSFeed},
		{"UX Collective", "https://uxdesign.cc/feed", processRSSFeed},
		{"r/userexperience", "https://www.reddit.com/r/userexperience/.rss", processRSSFeed},
		{"Microsoft Research Blog", "https://www.microsoft.com/en-us/research/feed/", processRSSFeed},
		{"Amazon Science", "https://www.amazon.science/feed.xml", processRSSFeed},
		{"ACM TechNews", "https://technews.acm.org/rss/technews_rss.xml", processRSSFeed},
		{"Hacker News (Best)", "https://hnrss.org/best", processRSSFeed},
		{"Ben Evans", "https://www.ben-evans.com/benedictevans?format=rss", processRSSFeed},
		{"First Round Review", "http://firstround.com/review/feed.xml", processRSSFeed},
		{"PyCoders Weekly", "https://pycoders.com/issues/rss", processRSSFeed},
		{"Postgres Weekly", "https://postgresweekly.com/rss", processRSSFeed},
		{"Quanta Magazine", "https://api.quantamagazine.org/feed/", processRSSFeed},
		{"O'Reilly Radar", "https://www.oreilly.com/radar/feed/", processRSSFeed},
		{"Rest of World", "https://restofworld.org/feed/latest/rss", processRSSFeed},
		{"It's Nice That", "https://www.itsnicethat.com/rss", processRSSFeed},
		{"AIGA Eye on Design", "https://eyeondesign.aiga.org/feed/", processRSSFeed},
		{"Colossal", "https://www.thisiscolossal.com/feed/", processRSSFeed},
		{"Brand New", "https://www.underconsideration.com/brandnew/feed/", processRSSFeed},
		{"Fstoppers", "https://fstoppers.com/feed", processRSSFeed},
		{"LensCulture", "https://www.lensculture.com/feed.rss", processRSSFeed},
		{"Creative Review", "https://www.creativereview.co.uk/feed/", processRSSFeed},
		{"Abduzeedo", "https://abduzeedo.com/rss.xml", processRSSFeed},
		{"Artsy", "https://www.artsy.net/rss/news", processRSSFeed},
		{"Design Week", "https://www.designweek.co.uk/feed/", processRSSFeed},
		{"Identity Designed", "https://identitydesigned.com/feed/", processRSSFeed},
		{"Bloomberg", "https://feeds.bloomberg.com/bview/rss.xml", processRSSFeed},
		{"The Economist", "https://www.economist.com/business-finance/rss.xml", processRSSFeed},
		{"Wall Street Journal (Opinion)", "https://feeds.a.dj.com/rss/RSSOpinion.xml", processRSSFeed},
		{"Morning Brew", "https://www.morningbrew.com/daily/rss", processRSSFeed},
		{"NerdWallet", "https://www.nerdwallet.com/blog/feed/", processRSSFeed},
		{"Farnam Street (FS Blog)", "https://fs.blog/feed/", processRSSFeed},
		{"James Clear (Atomic Habits)", "https://jamesclear.com/feed", processRSSFeed},
		{"Cal Newport's Blog", "https://www.calnewport.com/feed/", processRSSFeed},
		{"The Minimalists", "https://www.theminimalists.com/feed/", processRSSFeed},
		{"Seth's Blog", "http://feeds.feedblitz.com/sethgodin", processRSSFeed},
		{"National Geographic", "https://www.nationalgeographic.com/rss/all-stories.rss", processRSSFeed},
		{"Aeon", "https://aeon.co/feed.rss", processRSSFeed},
		{"Nautilus", "https://nautil.us/feed/", processRSSFeed},
		{"Knowable Magazine", "https://knowablemagazine.org/rss", processRSSFeed},
		{"STAT News", "https://www.statnews.com/feed/", processRSSFeed},
		{"Undark Magazine", "https://undark.org/feed/", processRSSFeed},
		{"The Conversation", "https://theconversation.com/us/articles.atom", processRSSFeed},
		{"The Atlantic", "https://www.theatlantic.com/feed/all/", processRSSFeed},
		{"Reuters", "http://feeds.reuters.com/reuters/topNews", processRSSFeed},
		{"Axios", "https://api.axios.com/feed/", processRSSFeed},
		{"Associated Press (AP)", "https://apnews.com/hub/ap-top-news/rss.xml", processRSSFeed},
		{"ProPublica", "https://www.propublica.org/feeds/propublica/main", processRSSFeed},
		{"The New Yorker", "https://www.newyorker.com/feed/everything", processRSSFeed},
		{"NPR", "https://feeds.npr.org/1001/rss.xml", processRSSFeed},
		{"Longform.org", "https://longform.org/feed.xml", processRSSFeed},
		{"Pitchfork", "https://pitchfork.com/rss/news/", processRSSFeed},
		{"LitHub", "https://lithub.com/feed/", processRSSFeed},
		{"The Paris Review", "https://www.theparisreview.org/feed", processRSSFeed},
		{"Brain Pickings (The Marginalian)", "https://www.themarginalian.org/feed/", processRSSFeed},
		{"Wirecutter", "https://www.nytimes.com/wirecutter/feed/", processRSSFeed},
		{"The Sweet Setup", "https://thesweetsetup.com/feed/", processRSSFeed},
		{"Tools and Toys", "https://toolsandtoys.net/feed/", processRSSFeed},
		{"Uncrate", "https://uncrate.com/feed/", processRSSFeed},
		{"Goop", "https://goop.com/feed/", processRSSFeed},
		{"The Prepared", "https://theprepared.com/feed/", processRSSFeed},
		{"Cool Hunting", "https://coolhunting.com/feed/", processRSSFeed},
		{"HODINKEE", "https://www.hodinkee.com/feed", processRSSFeed},
		{"The Onion", "https://www.theonion.com/rss", processRSSFeed},
		{"xkcd", "https://xkcd.com/rss.xml", processRSSFeed},
		{"SMBC (Saturday Morning Breakfast Cereal)", "https://www.smbc-comics.com/comic/rss", processRSSFeed},
		{"The Oatmeal", "http://feeds.feedburner.com/oatmealfeed", processRSSFeed},
		{"Cyanide & Happiness", "http://feeds.feedburner.com/Explosm", processRSSFeed},
		{"Dilbert Classics", "http://feed.dilbert.com/dilbert/classic", processRSSFeed},
		{"Reductress", "https://reductress.com/feed/", processRSSFeed},
		{"McSweeney's Internet Tendency", "https://www.mcsweeneys.net/articles/rss", processRSSFeed},
	}

	var wg sync.WaitGroup
	var totalInserted int32

	wg.Add(1)
	go func() {
		defer wg.Done()
		if inserted, err := dataFromWikipedia(); err == nil && inserted {
			fmt.Println("INFO: New data added from Wikipedia")
			atomic.AddInt32(&totalInserted, 1)
		}
	}()

	for _, src := range sources {
		s := src
		wg.Add(1)
		go func() {
			defer wg.Done()
			fmt.Printf("INFO: Fetching data from %s...\n", s.Name)
			if inserted, err := processSource(s); err == nil && inserted {
				fmt.Printf("INFO: New data added from %s\n", s.Name)
				atomic.AddInt32(&totalInserted, 1)
			}
		}()
	}

	wg.Wait()

	if totalInserted == 0 {
		fmt.Println("INFO: No new data added from any source")
	} else {
		fmt.Printf("INFO: Successfully added data from %d sources\n", totalInserted)
	}
}